---
- name: Load pull secret from vaulted file
  ansible.builtin.set_fact:
    ai_pull_secret: "{{ lookup('ansible.builtin.unvault', ai_pull_secret_file) | from_json }}"
    ai_pull_secret_string: "{{ lookup('ansible.builtin.unvault', ai_pull_secret_file) | from_json | to_json }}"
  no_log: true
